"""add user nonce

Revision ID: 16b1a523fbf2
Revises: a7e45a5de709
Create Date: 2026-06-29 00:16:49.975722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b1a523fbf2'
down_revision: Union[str, Sequence[str], None] = 'a7e45a5de709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nonce', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nonce')
    # ### end Alembic commands ###
