"""add unique constraints to session_topic table

Revision ID: 4356cac5bc95
Revises: d2f725892079
Create Date: 2026-07-01 10:35:35.348215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4356cac5bc95'
down_revision: Union[str, Sequence[str], None] = 'd2f725892079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_session_topic', 'session_topic', ['session_id', 'topic_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_session_topic', 'session_topic', type_='unique')
    # ### end Alembic commands ###
