"""feedback and access logs

Revision ID: 5ef949922019
Revises: 16b1a523fbf2
Create Date: 2026-06-30 07:53:08.681515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef949922019'
down_revision: Union[str, Sequence[str], None] = '16b1a523fbf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'FORM', name='feedbacktype'), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_submission',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assignment', sa.Column('due_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('assignment', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('assignment', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignment', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'assignment', 'user', ['created_by'], ['id'])
    op.add_column('assignment_submission', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('assignment_submission', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignment_submission', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'assignment_submission', 'user', ['updated_by'], ['id'])
    op.add_column('program', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('program', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'program', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'program', 'user', ['updated_by'], ['id'])
    op.add_column('program_permission', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('program_permission', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'program_permission', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'program_permission', 'user', ['updated_by'], ['id'])
    op.add_column('session', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('session', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'session', 'user', ['updated_by'], ['id'])
    op.add_column('session_permission', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('session_permission', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session_permission', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'session_permission', 'user', ['created_by'], ['id'])
    op.add_column('training_material', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('training_material', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'training_material', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'training_material', 'user', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_material', type_='foreignkey')
    op.drop_constraint(None, 'training_material', type_='foreignkey')
    op.drop_column('training_material', 'updated_by')
    op.drop_column('training_material', 'created_by')
    op.drop_constraint(None, 'session_permission', type_='foreignkey')
    op.drop_constraint(None, 'session_permission', type_='foreignkey')
    op.drop_column('session_permission', 'updated_by')
    op.drop_column('session_permission', 'created_by')
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'updated_by')
    op.drop_column('session', 'created_by')
    op.drop_constraint(None, 'program_permission', type_='foreignkey')
    op.drop_constraint(None, 'program_permission', type_='foreignkey')
    op.drop_column('program_permission', 'updated_by')
    op.drop_column('program_permission', 'created_by')
    op.drop_constraint(None, 'program', type_='foreignkey')
    op.drop_constraint(None, 'program', type_='foreignkey')
    op.drop_column('program', 'updated_by')
    op.drop_column('program', 'created_by')
    op.drop_constraint(None, 'assignment_submission', type_='foreignkey')
    op.drop_constraint(None, 'assignment_submission', type_='foreignkey')
    op.drop_column('assignment_submission', 'updated_by')
    op.drop_column('assignment_submission', 'created_by')
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.drop_column('assignment', 'updated_by')
    op.drop_column('assignment', 'created_by')
    op.drop_column('assignment', 'due_at')
    op.drop_table('feedback_submission')
    op.drop_table('feedback')
    # ### end Alembic commands ###
