"""add material_type to training_material

Revision ID: 9968b0d0725f
Revises: 5ef949922019
Create Date: 2026-06-30 14:44:54.782524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9968b0d0725f'
down_revision: Union[str, Sequence[str], None] = '5ef949922019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.add_column(
        "training_material",
        sa.Column(
            "material_type",
            sa.Text(),
            nullable=False,
            server_default="FILE"
        )
    )

    op.alter_column(
        "training_material",
        "material_type",
        server_default=None
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_material', 'material_type')
    # ### end Alembic commands ###
