"""added constraint to assignment submissions again

Revision ID: d2f725892079
Revises: 38e870c8f31c
Create Date: 2026-06-30 14:25:08.954410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f725892079'
down_revision: Union[str, Sequence[str], None] = '38e870c8f31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_assignment_submission_user_assignment', 'assignment_submission', ['user_id', 'assignment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_assignment_submission_user_assignment', 'assignment_submission', type_='unique')
    # ### end Alembic commands ###
