"""add google sub field

Revision ID: ed342ad14df0
Revises: 5e6ae509bf4e
Create Date: 2026-06-28 14:21:12.577650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed342ad14df0'
down_revision: Union[str, Sequence[str], None] = '5e6ae509bf4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_sub', sa.Text(), nullable=True))
    op.alter_column('user', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['google_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('user', 'google_sub')
    # ### end Alembic commands ###
